<?php
/**
 * Copyright © Getnet. All rights reserved.
 *
 * @author    Bruno Elisei <brunoelisei@o2ti.com>
 * See LICENSE for license details.
 */

/** @var \Getnet\SubSellerMagento\Block\Adminhtml\SubSeller\Form $tmpBlock */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<?php /** @var \Magento\Directory\Helper\Data $jsonHelper */
$jsonHelper = $tmpBlock->getData('directoryHelper');
$regionJson = /* @noEscape */ $jsonHelper->getRegionJson();
$scriptString = <<<script
require([
    "jquery",
    "mage/adminhtml/form"
], function(jQuery){
    var updater = new RegionUpdater(
        'address_country_id',
        'address_region',
        'address_region_id',
        {$regionJson},
        'disable'
    );
    updater.disableRegionValidation();
    window.updater = updater;
});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
