<?php
/**
 * Copyright © Getnet. All rights reserved.
 *
 * @author    Bruno Elisei <brunoelisei@o2ti.com>
 * See LICENSE for license details.
 */

/** @var \Getnet\SubSellerMagento\Block\Adminhtml\SubSeller\Form $form */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php if ($form): ?>
    <?= $form->toHtml() ?>
<?php endif; ?>
<script>
require([
    "jquery",
    "mage/mage"
], function($){
    $('#<?= $block->escapeJs($form->getForm()->getId()) ?>').mage('form').mage('validation');
});
</script>
